Rename To Datatrails
datatrails/datatrails-receipt-scitt pull request #13
Opened 2023-11-08 18:06 UTC by honourfish

## Overview
* rename all references to DataTrails
* ensure the default fqdn is the correct datatrails one

## Testing

tested using a known receipt:
```
$> datatrails_receipt_scittv1 verify -d <receipt>
```

```
{
  "anchor": "f29b54ec5f183ba17a434809bef8a06e457aa63cd99deab3bcb54715901f0910",
  "api_query": "https://app.datatrails.ai/archivist/v2/assets/-/events?order_by=SIMPLEHASHV2&proof_mechanism=SIMPLE_HASH&timestamp_accepted_since=2023-06-01T13:33:00Z&timestamp_accepted_before=2023-06-08T11:18:02Z",
  "endOperator": "lt",
  "endTimeRFC3339": "2023-06-08T11:18:02Z",
  "endTimeUnix": 1686223082,
  "eventCount": 1,
  "hashSchemaVersion": 2,
  "proofMechanism": 2,
  "startOperator": "gte",
  "startTimeRFC3339": "2023-06-01T13:33:00Z",
  "startTimeUnix": 1685626380,
  "tenant": "tenant/c8c51acf-5084-48ba-9e76-2c3cd9439818"
}
```
AB#8751

2023-11-08 18:07 UTC, honourfish commented on docs/conf.py
> +html_logo = "_static/DataTrails_WhtLogo_RGB.png"
NOTE: need a new logo here!

2023-11-09 10:04 UTC, honourfish commented on docs/conf.py
> +html_logo = "_static/DataTrails_WhtLogo_RGB.png"
thanks to Caitlin have a logo!

2023-11-09 10:08 UTC, j-hartley submitted a review, later dismissed

2023-11-09 10:08 UTC, j-hartley commented on README.rst
>  ==========================================
do we want to make this line a bit longer to match the title length?

2023-11-09 10:08 UTC, j-hartley commented on datatrails_receipt_scitt/namedproofs.py
> +See khipureceipt.py or simplehashreceipt.py for datatrails specific conveniences.
We should remove all mention of khipu while we are in here if possible please?

2023-11-09 10:08 UTC, j-hartley commented on docs/_static/DataTrails_WhtLogo_RGB.png.png
why .png.png?

2023-11-09 10:18 UTC, honourfish commented on docs/_static/DataTrails_WhtLogo_RGB.png.png
haha! good spot, it should only have 1 png

2023-11-09 10:19 UTC, honourfish commented on datatrails_receipt_scitt/namedproofs.py
> +See khipureceipt.py or simplehashreceipt.py for datatrails specific conveniences.
Can we keep the khipu removal to a separate PR? I am happy to do it, but i think its a better history if we do datatrails in one, and khipu in another?

2023-11-09 11:14 UTC, eccles requested changes

2023-11-09 11:14 UTC, eccles commented on .github/workflows/publish_package.yaml
> +#         cname: python-scitt.datatrails.com
datatrails.ai

2023-11-09 11:14 UTC, eccles commented on docs/index.rst
> +Keep an eye on `DataTrails Docs <https://docs.datatrails.com/docs/overview/introduction/>`_ For guides and howto's
datatrails.ai

2023-11-09 13:54 UTC, honourfish commented on docs/_static/DataTrails_WhtLogo_RGB.png.png
done

2023-11-09 13:55 UTC, honourfish commented on README.rst
>  ==========================================
done!

2023-11-09 13:55 UTC, honourfish commented on datatrails_receipt_scitt/namedproofs.py
> +See khipureceipt.py or simplehashreceipt.py for datatrails specific conveniences.
defering to a different PR :)

2023-11-09 14:02 UTC, eccles approved these changes

2023-11-09 14:09 UTC, merged